### ISSUE TITLE
English Subtitles for " Teaching with Julia (my experience)" by Daniel Molina (JuliaCon 2022)

### ISSUE THREAD

**Issue by digital-carver** [JuliaCommunity/YouTubeVideoSubtitles#4]
Hi, 

I have edited and synced the subtitles for [Teaching with Julia (my experience) | Daniel Molina | JuliaCon 2022](https://www.youtube.com/watch?v=CwDntVE3SHU), and published it on Amara: https://amara.org/en/videos/RBQrUGB7E1zM/en/4084505/

I've made my best effort to interpret it wherever the pronunciation is hard to understand, based on on-screen information and contextual details, but still have had to mark three small portions as `[inaudible]`:  one short phrase at [03:41](https://youtu.be/CwDntVE3SHU?t=221), one long phrase at [03:52](https://youtu.be/CwDntVE3SHU?t=232), and one short phrase at [06:59](https://youtu.be/CwDntVE3SHU?t=419).

I've used the original wording as it is in order to match the audio, even when the grammar isn't fully correct. But in a few instances, where the original wording might make it hard to understand what's being said, I've made some small grammar corrections. 

I hope this work is of some use. Please let me know if I need to make any changes. 

-- 
Sundar R

**Comment by miguelraz** [comment]
Thank you, I've uploaded the subtitles, correcting only the phrase at 3:43, the others I couldn't understand either.
